### ISSUE TITLE
Deprecate, rather than replace, existing organisation fields

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/ocds_parties_extension#2]
The current draft of the extension replaces Organization blocks with Organization references. 

Instead we need for version 1.1 of OCDS to add the new id field, and to **deprecate** most other fields of the organization block.

This depends on input from tech team on best way to mark deprecation in the schema.

**Comment by jpmckinney** [comment]
Moved https://github.com/open-contracting/ocds-extensions/issues/14
