### ISSUE TITLE
Improve definition of 'Buyer'

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/ocds_parties_extension#5]
The current definition of 'Buyer' is "The buyer is the entity whose budget will be used to purchase the goods."

This appears wrong on a number of levels.

(1) We now recognise (via an extension) multi-source budgets;

(2) OCDS does not only apply to 'goods'

An improved, but backwards compatible, definition of buyer is needed.

**Comment by jpmckinney** [comment]
Moved https://github.com/open-contracting/ocds-extensions/issues/12
